export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const QUESTIONS_FETCH_REQUEST = 'QUESTIONS_FETCH_REQUEST';
export const QUESTIONS_FETCH_SUCCESS = 'QUESTIONS_FETCH_SUCCESS';
export const ANSWER_SELECTED = 'ANSWER_SELECTED';
export const GAME_RESET = 'GAME_RESET';
export const SUBMIT_QUESTION = 'SUBMIT_QUESTION';

export const GET_USER_INFO = 'GET_USER_INFO' 


export const USERS_FETCH_REQUEST = 'USERS_FETCH_REQUEST';
export const USERS_FETCH_SUCCESS = 'USERS_FETCH_SUCCESS';
export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const EDIT_USER = 'EDIT_USER';
export const EDIT_USER_MODAL = 'EDIT_USER_MODAL'
export const CHANGE_DATA_EDIT_USER_MODAL = 'CHANGE_DATA_EDIT_USER_MODAL'



